import {
  ExternalLink,
  HardDrive,
  Info,
  Radar,
  Server,
  ShieldCheck,
} from 'lucide-react';

import { AppShell } from '../../components/app-shell';

const githubRepositoryUrl = 'https://github.com/Bigda7/jobradar-frontend';

const sections = [
  {
    title: 'Privacy at a glance',
    icon: ShieldCheck,
    paragraphs: [
      'JobRadar is currently a personal, non-commercial job search workspace. It does not provide user accounts, payments, advertising, or behavioral analytics.',
      'The application does not use advertising cookies or third-party analytics. If that changes, this notice and any required consent controls will be updated before those tools are enabled.',
    ],
  },
  {
    title: 'Data stored in your browser',
    icon: HardDrive,
    paragraphs: [
      'Your color theme preference and Job Tracker records are stored in localStorage on the device and browser you are using. Tracker records can include vacancy snapshots, application status, and notes you enter.',
      'Tracker data is not sent to the JobRadar backend, is not encrypted, and is not backed up. Clearing this site’s browser storage removes it. Do not place passwords, access tokens, financial information, medical information, or other sensitive data in tracker notes.',
    ],
  },
  {
    title: 'Service delivery and technical logs',
    icon: Server,
    paragraphs: [
      'The web application is delivered through Vercel and the JobRadar API is hosted on Amazon Web Services. These providers and the application server may process standard technical request data, such as an IP address, browser information, requested path, and timestamp, to deliver, secure, and troubleshoot the service.',
      'JobRadar does not use technical request data for advertising or to build user profiles. Operational log retention follows the active infrastructure configuration and the applicable provider policies.',
    ],
  },
  {
    title: 'Vacancy data and external services',
    icon: Radar,
    paragraphs: [
      'JobRadar collects vacancy information from identified third-party job boards, freelance platforms, feeds, and public applicant-tracking sources. Job listings, company names, trademarks, and source content remain the property of their respective owners.',
      'Each available vacancy link opens the original source. JobRadar is not affiliated with or endorsed by the listed employers or platforms, and it cannot guarantee that a vacancy remains available or that source information is complete, current, or error-free.',
    ],
  },
  {
    title: 'Automated matching',
    icon: Info,
    paragraphs: [
      'Match scores are generated by deterministic rules configured for the current personal search profile. They are organizational aids, not hiring decisions, professional advice, or guarantees of suitability.',
    ],
  },
];

export function LegalPage() {
  return (
    <AppShell>
      <main
        id="main-content"
        tabIndex={-1}
        className="premium-scrollbar min-h-[calc(100vh-64px)] min-w-0 overflow-y-auto bg-canvas outline-none lg:h-screen lg:min-h-0"
      >
        <header className="border-b border-white/[0.06] bg-panel px-4 py-5 sm:px-6 lg:px-7">
          <div className="flex items-center gap-2 text-xs text-zinc-500">
            <span>Radar</span>
            <span>/</span>
            <span className="text-zinc-400">Information</span>
          </div>
          <div className="mt-1.5 flex flex-wrap items-baseline gap-3">
            <h1 className="text-xl font-semibold tracking-[-0.035em] text-white">
              Privacy &amp; legal
            </h1>
            <span className="text-xs text-zinc-500">
              Personal, non-commercial workspace
            </span>
          </div>
          <p className="mt-3 max-w-3xl text-sm leading-6 text-zinc-400">
            A plain-language summary of how the current JobRadar application
            handles browser data, technical requests, and third-party vacancy
            information.
          </p>
        </header>

        <div className="mx-auto w-full max-w-5xl px-4 py-6 sm:px-6 lg:px-7 lg:py-8">
          <div className="grid gap-4 md:grid-cols-2">
            {sections.map(({ title, icon: Icon, paragraphs }, index) => (
              <section
                key={title}
                aria-labelledby={`legal-section-${index}`}
                className={`rounded-2xl border border-white/[0.07] bg-card p-5 sm:p-6 ${
                  index === sections.length - 1 ? 'md:col-span-2' : ''
                }`}
              >
                <div className="flex items-center gap-3">
                  <span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl border border-white/[0.07] bg-white/[0.035] text-radar">
                    <Icon className="h-4 w-4" aria-hidden="true" />
                  </span>
                  <h2
                    id={`legal-section-${index}`}
                    className="text-sm font-semibold text-zinc-200"
                  >
                    {title}
                  </h2>
                </div>
                <div className="mt-4 space-y-3 text-sm leading-6 text-zinc-400">
                  {paragraphs.map((paragraph) => (
                    <p key={paragraph}>{paragraph}</p>
                  ))}
                </div>
              </section>
            ))}
          </div>

          <section
            aria-labelledby="legal-contact-title"
            className="mt-4 rounded-2xl border border-white/[0.07] bg-white/[0.025] p-5 sm:p-6"
          >
            <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
              <div>
                <h2
                  id="legal-contact-title"
                  className="text-sm font-semibold text-zinc-200"
                >
                  Questions and updates
                </h2>
                <p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-400">
                  Use the GitHub repository contact channels for technical or
                  privacy questions. Do not include sensitive personal data in
                  a public issue.
                </p>
              </div>
              <a
                href={githubRepositoryUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex h-10 shrink-0 items-center justify-center gap-2 rounded-xl border border-white/[0.08] bg-white/[0.035] px-4 text-xs font-medium text-zinc-300 transition-colors hover:border-radar/25 hover:bg-radar/[0.06] hover:text-radar focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-radar/70"
              >
                Open repository
                <ExternalLink className="h-3.5 w-3.5" aria-hidden="true" />
              </a>
            </div>
          </section>

          <p className="mt-5 text-center text-[11px] text-zinc-500">
            Last updated September 6, 2026
          </p>
        </div>
      </main>
    </AppShell>
  );
}
